-- AlterTable: Add ARTICLE and TOURNAMENT_CARD to the PostType enum
ALTER TABLE `post` MODIFY `type` ENUM('NOTIFICATION', 'NEWS', 'ARTICLE', 'POLL', 'TOURNAMENT_CARD') NOT NULL DEFAULT 'NOTIFICATION';
