export const attendanceDashboardTableColumns = [
  { key: "date", label: "Date" },
  { key: "memberId", label: "Member ID" },
  { key: "member", label: "Member" },
  { key: "role", label: "Role" },
  { key: "teamId", label: "Team ID" },
  { key: "teamName", label: "Team Name" },
  { key: "status", label: "Status" },
  { key: "punchInAt", label: "Punch In" },
  { key: "punchOutAt", label: "Punch Out" },
  { key: "workedHours", label: "Worked Hrs" },
  { key: "lateMinutes", label: "Late (min)" },
  { key: "punchInValid", label: "Check-In Valid" },
  { key: "punchOutValid", label: "Check-Out Valid" },
  { key: "punchInDistanceMeters", label: "Check-In Distance" },
  { key: "punchOutDistanceMeters", label: "Check-Out Distance" },
  { key: "punchInCoordinates", label: "Check-In Coordinates" },
  { key: "punchOutCoordinates", label: "Check-Out Coordinates" },
];
